# PostgreSQL.
# Install the pg driver:
#   gem install pg
development:
  adapter: postgresql
  encoding: unicode
  database: friends
  pool: 5
  username: krantos
  # password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: friends_test
  pool: 5
  username: krantos
  # password:
  timeout: 5000